### ISSUE TITLE
Dockerize Discord service

### ISSUE THREAD

**Issue by milivojm** [CntoDev/level-up#106]
Discord service ideally needs to be deployed as Docker container too. 

- add dockerfile for service in `container` folder
- update `build-docker.sh`
- update `Build-docker.ps1`

**Comment by milivojm** [comment]
@enrico-ghidoni - should we build a docker compose yaml for development? I'm not running stuff in docker locally (except postgres & rabbitmq).

**Comment by enrico-ghidoni** [comment]
Yeah let's make this part of a different epic to review the current container system. `build-docker` scripts should not be necessary as we decided to move to docker compose anyway.

I'll open a discussion on improving the setup for a development environment as well as replacing some manual scripts.
