### ISSUE TITLE
Application Form: Enhance Time Zone Selection

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/level-up#126]
Currently the Time Zone selection has a couple of issues which make it less userfriendly for applicants:

1.) Each single timezone has multiple representatives making the drop down field much longer than needed. E.g. UTC-7 is represented with 16 example cities. Each timezone should be represented with 1-3 examples max.

2.) Our community is mostly CET (UTC+1) / CEST (UTC+2) focused, yet the drag and drop field starts at UTC-11. Can we select by default CET / CEST and then have the drag and drop go up and down in sections?

3.) The Time zone selection menu should have a short explanation or question below it to clarify what we are asking. In our current application form on enjin this would be "What UTC time zone are you from?" as well as a link so people can find their timezone accurately: https://www.timeanddate.com/time/map/

Sidenote: does the Time Zone selection menu in the application form automatically update UTC according to summer time shifts? I.e. Central European Time (CET) is UTC+1 but Central European Summer Time (CEST) is UTC+2. Both are located in the Berlin/Paris region.

**Comment by milivojm** [comment]
Hi!

[Timezone dropdown](https://github.com/CntoDev/rooster/blob/develop/src/Roster.Web/Areas/Roster/Pages/ApplicationForm/Apply.cshtml#L27) is created using data from [here](https://github.com/CntoDev/rooster/blob/develop/src/Roster.Web/Areas/Roster/Pages/ApplicationForm/Apply.cshtml.cs#L185). This in turn is filled from https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=net-6.0

**Comment by milivojm** [comment]
> Sidenote: does the Time Zone selection menu in the application form automatically update UTC according to summer time shifts? I.e. Central European Time (CET) is UTC+1 but Central European Summer Time (CEST) is UTC+2. Both are located in the Berlin/Paris region.

It's unlikely. See https://stackoverflow.com/questions/2961848/how-to-use-timezoneinfo-to-get-local-time-during-daylight-saving-time for more.

**Comment by JamesTheClarke** [comment]
> [Timezone dropdown](https://github.com/CntoDev/rooster/blob/develop/src/Roster.Web/Areas/Roster/Pages/ApplicationForm/Apply.cshtml#L27) is created using data from [here](https://github.com/CntoDev/rooster/blob/develop/src/Roster.Web/Areas/Roster/Pages/ApplicationForm/Apply.cshtml.cs#L185). This in turn is filled from https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=net-6.0

Is it possible for us to pull that data and then pre-select UTC+1 as the default option? Because as is the vast majority of our users will currently have to scroll down from UTC-11 to UTC-1, UTC+0, UTC+1 or UTC+2. Considering the amount of different options for each UTC in the list that's a lot of unecessary scrolling we could optimise for them.

**Comment by milivojm** [comment]
Yes, it is. It's also possible to filter out unwanted time zones.

**Comment by enrico-ghidoni** [comment]
Merged with related issues into #133
