### ISSUE TITLE
List of Applications: Edit & Comment History

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/level-up#129]
https://rooster.carpenoctem.co/Roster/ApplicationForm/ListApplications

Sidenote: I'd rename `List applications` to `List of Applications`.

Main issue: currently there is no tracking of who accepted or rejected applications and why. The following features would be great to keep similar records to our current enjin application process.

- [ ] it needs to be visible who accepted or rejected an application.
- [ ] it needs to be visible when an application was accepted or rejected
- [ ] when an application is rejected a reason should be given and tracked as a comment.
- [ ] Interviewers, Corporals and SSgts need to be able to leave private comments (not visible to the applicant) on each application. This is used to identify red flags collectively before the interview starts, thus the interviewer has all the necessary information in one single location. It also serves to leave comments in cases one doesn't hear from the applicant in time. Examples:
  - https://www.carpenoctem.co/dashboard/applications/application?app_id=10019820
  - https://www.carpenoctem.co/dashboard/applications/application?app_id=10003487
  - https://www.carpenoctem.co/dashboard/applications/application?app_id=10009590
- [ ] Interviewers should be able to leave public comments visible to the applicant. This is used to inform them either a.) that the application meets our standards and they should contact us on TS or Discord for and interview or b.) it does not meet our standards and has been rejected outright.

**Comment by enrico-ghidoni** [comment]
Activity logs are a planned feature, see #131. The core idea is that every action performed either by users or by the system will get reported to allow for better tracing of *who did what* and *when*.

From there it will be trivial to add those details to the list of application forms.

Concerning private and public comments on the application form, we'll keep this on the to-do list. I'm wondering whether it's necessary for replacing the old Roster or not.

**Comment by JamesTheClarke** [comment]
> Concerning private and public comments on the application form, we'll keep this on the to-do list. I'm wondering whether it's necessary for replacing the old Roster or not.

This feature would definitely still be very appreciated. The onboarding process isn't always handled by the same person at the three different stages. Thus it can be very helpful to look up what another person has observed during an Interview for example or what kind of redflags were noticed in the application. For record keeping it was often also useful in the past when an escalation occured and I was able to check if anyone noticed something early on or if that person kinda flew under the radar.

Currently enjin has some limitations in collaborative onboarding, thus interviewers mix the roster, the application comment section the interviewing discord channel and the forums to share information, however that means sometimes you have to look in various areas to get up to speed. If possible it would be ideal if the new roster could track the various stages of the onboarding process and become the single point of information storage / sharing for all involved staff members.

**Comment by enrico-ghidoni** [comment]
Don't get me wrong I agree that streamlining the whole workflow is the end-goal of Rooster. I'm just trying to filter out features that are critical for v1 and those that will be a good addition later down the line.

I noticed old Roster has a "Notes" section for each recruit (and member in general). Not a big fan of generic note text. We can use that a temporary solution if required and move to a more structured system as you mentioned in your first message.

**Comment by enrico-ghidoni** [comment]
Merged with related issues into #133
