### ISSUE TITLE
Application Form: Separation of Application and Member List

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/level-up#132]
In my view the Application Form should be limited to what we need to initially process a recruit. If the form is too lenghty it can be intimidating and potentially deter people from filling it out.

The following field should not be present in the application but instead be able to be edited by interviewers, moderators and admins in the member profile during different stages of the onboarding process (similar to how interviewers currently add the BI account username after mod assessment & bootcamp):

- `Bohemia Interactive nickname` should be renamed to `Bohemia Interactive Account Username` as this is what BI references on their Arma 3 Unit Page.
- `Discord username` should be renamed to `Discord Profile ID`, usernames can change, the ID is a unique identifyer.
- `GitHub nickname` should be renamed to `GitHub Account Name`, the nickname could be misleading because you can give yourself a nicer looking profile nickname. Example my profile's nickname is "Clarke", my account name is "JamesTheClarke": https://github.com/JamesTheClarke
- `Google e-mail`should be renamed to `Gmail Address`
- `Steam username` should be renamed to `Steam ID` for the same reason as with GitHub / Discord, one can change the username, but the ID (17-digit number) is permanent.
- `Teamspeak ID` should be renamed `TeamSpeak ID` just to keep things uniform (see GitHub).

This would cut six fields from the application form and the most important three (Discord, BI Account and TS ID) can be filled in by Interviewers at different stages of the onboarding process.

**Comment by enrico-ghidoni** [comment]
Merged with related issues into #133
