### ISSUE TITLE
Warnings system

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#64]
There are several warnings to be shown to both Interviewers and Member Managers.

 - when a member hasn't attended enough events (2 events in the past month)
 - when a recruit's 8 week probation phase is close to ending
 - when a recruit is close to not fulfilling their mod assessment (due 2 weeks from joining)

I'm sure there are going to be many other warnings that are either already in the `django-roster` or that could be useful to introduce. But I would stop with the three listed above for the MVP.

For the UX bit, different roles should see different warnings and only relative to their branch. For example, Interviewers should not be able to see warnings for Member Managers and viceversa. Also, displaying the warnings on the frontend should allow for some basic search and filtering features.

@milivojm if you agree this is enough for the MVP I can go ahead and split this into different sub-tasks.

**Comment by milivojm** [comment]
Do we need this for MVP? Or at all?
