### ISSUE TITLE
Assigning ranks to members

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#66]
Make all Ranks available (Recruit, Reservist, Grunt, Specialist, Corporal and Staff Sergeant) for promoting/demoting members.

Different ranks can be assigned by different people, thus the permission system should be updated accordingly.

I am not currently aware whether the community already has guidelines for which ranks/branch members can assign which ranks to other members (pinging @JamesTheClarke here to make sure). But ideally it should be something like this:
 - only Interviewers and SSgts can promote a Recruit to the Reservist rank
 - only Member Managers and SSgts can promote/demote Reservists, Grunts and Specialists to either three of those ranks (although a valid alternative would be to make only Branch managers be able to promote members to the Specialist rank, but that would require the Branch system to be in place so it can wait)
 - only SSgts can promote members to Corporal and Staff Sergeant

**Comment by milivojm** [comment]
Interviewing promotes from RCT to RES.
SSGT promote SPC, CPL, SSGT.

System could automatically promote/demote RES/GNT based on attendance data.
