### ISSUE TITLE
MVP Automation level

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#68]
Opening this to centralize the discussion about whether automation of features mentioned in #62, #63, #64, #66 should be part of the MVP milestone.

Whilst it is definitely something we want in the Roster, I think implementing it right away creates two different issues:

 1. Longer development time. In my opinion MVP should be delivered as fast as we possibly can so we don't have to maintain the `django-roster` project anymore. Developing automation from the get go would significantly increase time to transition. Also, I do think we need to keep the manual version of those features anyway in case something breaks or for control purposes, then build automation on top of that.
 2. Explitic reasoning. Whilst this mostly concerns #64 the idea is still valid: automation must be transparent, in the sense that every action taken by some "reasoning" must be shown to end users (Interviewers or Member Managers). An event-oriented design for the automation feature would work great to support reasoning, but it would take some time to discuss, design and finally implement.

**Comment by milivojm** [comment]
Closing with #81 pull request.
