### ISSUE TITLE
Event tracking

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#69]
Discussion for how the attendance tracker should work.

The `django-roster` uses a complicated way of parsing an list of attendees through Steam's API every X time during a scheduled event (Tuesday and Friday). We could greatly simplify the logic, pasting Discord convo between myself and @milivojm.

 1. Define the concept of community event and make it editable by someone (i.e. Tuesday and Friday events with start and end time). This means defining something like **ArmaEventRecurrence** that should be editable by users to identify community events that we want to gather attendance data of. 
 2. Have something kick off an event tracker at the start of each event, essentially starting a recording of what happens on the server. MassTransit can handle scheduled domain events (i.e. **ArmaEventStarted**) and it already works for handling the recruitment stage.
 3. Have a set of code that constantly (i.e. every minute) checks who is online through Steam's API and matches the retrieved usernames with the members of the community (from Roster). The frequency of polling Steam API can be arbitrarily changed and should be included in a setting. Do we keep data in memory (dangerous if the service breaks) or do we store it in the DB (slower)?
 4. Once the event has finished, the tracking script should update the attendance for said event in a streamlined format (i.e. only username and attendance ratio, like what percentage he/she/they were logged with respect to the event duration). The attendance service could raise a storm of **ArmaEventAttended** with information regarding **Nickname, Ratio, ArmaEventId** and consumers can then store the data in the DB.
 5. Take it from there on the domain level to check attendance (i.e. attendance over 50% means event attended). On the domain level we can issue a **EnoughEventsAttended** event for recruits when they attend more than the required amount of events within 8 weeks and a **MemberWarning** event for existing members (Reservists and above) if their attendance ratio drops below the minimum required.

**Comment by milivojm** [comment]
This one will probably wait, we will cheat around by peaking into old roster's table.

**Comment by milivojm** [comment]
Right now end user can use a form action to explicitly state member has attended enough events. This one might be really too much for MVP?
