### ISSUE TITLE
Consume `MemberPromoted` events

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#89]
Connect `DiscordService` to MassTransit event bus. Service should subscribe to `MemberPromoted` events

**Comment by enrico-ghidoni** [comment]
@milivojm what triggers the `MemberPromoted` event in the current release? Or is it something that still needs to be done?

**Comment by milivojm** [comment]
Just end of recruitment process, from recruit -> reservist. Manual promotions do not exist yet.
