### ISSUE TITLE
Obtain Discord's `RoleId` from Roster `RankId`

### ISSUE THREAD

**Issue by enrico-ghidoni** [CntoDev/level-up#91]
Upon receiving a `MemberPromoted` event, `DiscordService` should retrieve the `RoleId` relative to the Discord universe that corresponds to `RankId` in the Roster world for both the previous member rank and the new member rank.

**Comment by enrico-ghidoni** [comment]
@milivojm could you add the rank as a string too in the `MemberPromoted` event so its corresponding Discord ID can be retrieved without querying the DB?

**Comment by milivojm** [comment]
Ok.
